server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Redirigir cualquier petición que no sea un archivo físico hacia index.html
        try_files $uri $uri/ /index.html;
    }

    # Desactivar logs innecesarios para favicon y assets para optimizar I/O
    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }

    # Manejo de compresión gzip para acelerar la carga de assets
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
